name: countryinfo
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1



environment:
  sdk: '>=3.4.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  get_storage: ^2.1.1
  lottie: ^3.1.0
  text_marquee: ^0.0.2
  skeletonizer: ^1.3.0
  kt_dart: ^1.1.0
  flutter_cache_manager: ^3.3.0
  dio: ^5.4.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2
  auto_route: ^8.1.3
  hooks_riverpod: ^2.5.1
  flutter_overlay_loader: ^2.0.0
  loading_animation_widget: ^1.2.1
  flutter_screenutil: ^5.9.0
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^9.2.1
  decimal: ^2.3.3  
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^3.0.0
  faker: ^2.1.0
  another_flutter_splash_screen: ^1.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  freezed: ^2.4.7
  build_runner: null




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mob_app_logo.png"





  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/logoes/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
  
  
  
